# Generated by Django 2.2.7 on 2020-03-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='passconf',
            field=models.CharField(default=1234, max_length=50),
            preserve_default=False,
        ),
    ]
